import { NextRequest, NextResponse } from "next/server";

type OpenLibraryBook = { cover?: { small?: string; medium?: string; large?: string } };
type OpenLibrarySearchDoc = { title?: string; author_name?: string[]; cover_i?: number };
type OpenLibrarySearchResponse = { docs?: OpenLibrarySearchDoc[] };
type GoogleBook = { volumeInfo?: { title?: string; authors?: string[]; imageLinks?: { smallThumbnail?: string; thumbnail?: string; small?: string; medium?: string; large?: string; extraLarge?: string } } };
type GoogleBooksResponse = { items?: GoogleBook[] };
type MatchResult = { score: number; accepted: boolean };
type TitleEvidence = { score: number; exact: boolean; adjacent: boolean; coverage: number; keywordCount: number; keywordMatches: number };
type CoverOption = { url: string; source: string; score: number };

const responseHeaders = { "Cache-Control": "public, s-maxage=86400, stale-while-revalidate=604800" };
const TITLE_STOP_WORDS = new Set(["a","an","and","as","at","book","by","edition","for","from","in","into","novel","of","on","or","series","the","to","volume","with"]);
function httpsImage(url?: string){return url?.replace(/^http:\/\//i,"https://");}
function normalizeText(value?: string){return (value||"").normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function textWords(value?: string){return normalizeText(value).split(" ").filter(Boolean);}
function titleKeywords(value?: string){const allWords=textWords(value);const significant=allWords.filter(w=>w.length>1&&!TITLE_STOP_WORDS.has(w));return significant.length?[...new Set(significant)]:[...new Set(allWords)];}
function looksLikeSeriesMetadata(value:string){const text=value.trim();return /#\s*\d+(?:\.\d+)?\b/i.test(text)||/\b(?:book|volume|vol\.?|part)\s*(?:#|no\.?\s*)?\d+(?:\.\d+)?\b/i.test(text)||/\b(?:series|duet|trilogy|saga)\b[^\d]{0,30}\d+(?:\.\d+)?\b/i.test(text);}
function stripGoodreadsSeriesSuffix(title:string){let cleaned=title.trim();for(let pass=0;pass<3;pass++){const match=cleaned.match(/\s*[\(\[]([^\)\]]+)[\)\]]\s*$/);if(!match||!looksLikeSeriesMetadata(match[1]))break;cleaned=cleaned.slice(0,match.index).trim();}cleaned=cleaned.replace(/\s*[-–—:]\s*(?:book|volume|vol\.?|part)\s*(?:#|no\.?\s*)?\d+(?:\.\d+)?\s*$/i,"").trim();return cleaned||title.trim();}
function addUsefulVariant(values:string[],candidate?:string){const value=candidate?.trim();if(!value)return;const keywords=titleKeywords(value);if(!keywords.length)return;values.push(value);}
function titleVariants(title:string){const original=title.trim(),seriesCleaned=stripGoodreadsSeriesSuffix(original),candidates:string[]=[];addUsefulVariant(candidates,seriesCleaned);addUsefulVariant(candidates,original);for(const value of [seriesCleaned,original]){const subtitle=value.split(/\s*[:–—]\s*/)[0]?.trim();if(subtitle&&titleKeywords(subtitle).length>=2)addUsefulVariant(candidates,subtitle);const trailing=value.replace(/\s*[\(\[][^\)\]]+[\)\]]\s*$/,"").trim();if(trailing&&titleKeywords(trailing).length>=2)addUsefulVariant(candidates,trailing);}const seen=new Set<string>();return candidates.filter(v=>{const k=normalizeText(v);if(!k||seen.has(k))return false;seen.add(k);return true;});}
function authorEvidence(requestedAuthor:string,candidateAuthors:string[]){const wanted=normalizeText(requestedAuthor);if(!wanted)return 0;const wantedWords=textWords(wanted),last=wantedWords.at(-1);let best=0;for(const candidate of candidateAuthors){const found=normalizeText(candidate);if(!found)continue;if(found===wanted||found.includes(wanted)||wanted.includes(found)){best=Math.max(best,8);continue;}const set=new Set(textWords(found));const shared=wantedWords.filter(w=>set.has(w)).length,overlap=wantedWords.length?shared/wantedWords.length:0;if(last&&set.has(last))best=Math.max(best,5);if(overlap>=.67)best=Math.max(best,4);else if(overlap>=.5)best=Math.max(best,3);}return best;}
function titleEvidence(requestedTitle:string,candidateTitle?:string):TitleEvidence{const wanted=normalizeText(requestedTitle),found=normalizeText(candidateTitle);if(!wanted||!found)return{score:0,exact:false,adjacent:false,coverage:0,keywordCount:0,keywordMatches:0};const wk=titleKeywords(wanted),fs=new Set(titleKeywords(found)),matches=wk.filter(w=>fs.has(w)).length,coverage=wk.length?matches/wk.length:0;let score=0,exact=false,adjacent=false;if(found===wanted){score=14;exact=true;}else if(found.includes(wanted)||wanted.includes(found)){score=11;adjacent=true;}else{score=coverage*9;if(coverage>=.75)score+=1;if(matches>=2&&coverage>=.5)score+=.5;}return{score,exact,adjacent,coverage,keywordCount:wk.length,keywordMatches:matches};}
function matchCandidate(requestedTitle:string,requestedAuthor:string,candidateTitle?:string,candidateAuthors:string[]=[]):MatchResult{const matches=titleVariants(requestedTitle).map(v=>titleEvidence(v,candidateTitle)).sort((a,b)=>b.score-a.score),best=matches[0];if(!best||best.score<=0)return{score:0,accepted:false};const as=authorEvidence(requestedAuthor,candidateAuthors),has=Boolean(normalizeText(requestedAuthor)),score=best.score+as;let accepted=false;if(!has)accepted=best.exact||best.adjacent||best.coverage>=.5||best.keywordMatches>=2;else if(as>=7)accepted=best.exact||best.adjacent||best.keywordMatches>=1||best.coverage>=.1;else if(as>=5)accepted=best.exact||best.adjacent||best.keywordMatches>=1||best.coverage>=.2;else if(as>=3)accepted=best.exact||best.adjacent||best.coverage>=.5||best.keywordMatches>=2;if(has&&best.keywordCount<=1&&as<3)accepted=false;if(!best.exact&&!best.adjacent&&best.keywordMatches<1)accepted=false;return{score,accepted};}
function keywordSearchText(title:string,author:string){const keywords=titleKeywords(title).slice(0,6),last=textWords(author).at(-1);return[...keywords,last].filter(Boolean).join(" ");}
function cleanRelatedIsbn(value:string){const cleaned=value.replace(/[^0-9Xx]/g,"");return /^(?:\d{13}|\d{9}[\dXx])$/.test(cleaned)?cleaned:null;}
function isbn10From(value:string){const cleaned=cleanRelatedIsbn(value);if(!cleaned)return null;if(cleaned.length===10)return cleaned.toUpperCase();if(!cleaned.startsWith("978"))return null;const core=cleaned.slice(3,12);const total=[...core].reduce((sum,digit,index)=>sum+(10-index)*Number(digit),0);const check=(11-(total%11))%11;return core+(check===10?"X":String(check));}
async function amazonHighResCoverByIsbn(isbn:string):Promise<CoverOption[]>{const isbn10=isbn10From(isbn);if(!isbn10)return[];const url=`https://m.media-amazon.com/images/P/${encodeURIComponent(isbn10)}.01._SCRM_SL2000_.jpg`;try{const response=await fetch(url,{method:"HEAD",redirect:"follow",cache:"no-store",headers:{"User-Agent":"Shelf-of-Fame cover lookup"}});if(!response.ok)return[];const type=(response.headers.get("content-type")||"").toLowerCase();if(!type.startsWith("image/jpeg"))return[];const size=Number(response.headers.get("content-length")||0);if(size&&size<5000)return[];return[{url,source:"Amazon High-Res",score:35}];}catch{return[];}}
function decodeHtml(value:string){return value.replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">");}
function htmlText(value:string){return decodeHtml(value.replace(/<[^>]+>/g," ").replace(/\s+/g," ")).trim();}
async function libraryThingRelatedIsbns(isbn:string){const token=process.env.LIBRARYTHING_API_TOKEN?.trim();if(!token||!isbn)return[];const response=await fetch(`https://www.librarything.com/api/${encodeURIComponent(token)}/thingISBN/${encodeURIComponent(isbn)}`,{next:{revalidate:86400}});if(!response.ok)return[];const xml=await response.text();const related=[...xml.matchAll(/<isbn>([^<]+)<\/isbn>/gi)].map(m=>cleanRelatedIsbn(m[1])).filter((v):v is string=>Boolean(v)&&v!==isbn);return[...new Set(related)].slice(0,10);}
async function libraryThingIsbnsByTitle(title:string){const token=process.env.LIBRARYTHING_API_TOKEN?.trim(),searchTitle=stripGoodreadsSeriesSuffix(title);if(!token||!searchTitle)return[];const response=await fetch(`https://www.librarything.com/api/${encodeURIComponent(token)}/thingTitle/${encodeURIComponent(searchTitle)}`,{next:{revalidate:86400}});if(!response.ok)return[];const xml=await response.text(),returned=xml.match(/<title>([^<]+)<\/title>/i)?.[1]?.trim();if(returned){const e=titleEvidence(searchTitle,returned);if(!(e.exact||e.adjacent||e.coverage>=.5||e.keywordMatches>=2))return[];}return[...new Set([...xml.matchAll(/<isbn>([^<]+)<\/isbn>/gi)].map(m=>cleanRelatedIsbn(m[1])).filter((v):v is string=>Boolean(v)))].slice(0,10);}
async function libraryThingPopularCoversByTitle(title:string,author:string):Promise<CoverOption[]>{const searchTitle=stripGoodreadsSeriesSuffix(title);if(!searchTitle)return[];try{const response=await fetch(`https://www.librarything.com/title/${encodeURIComponent(searchTitle)}`,{redirect:"follow",next:{revalidate:86400},headers:{"User-Agent":"Shelf-of-Fame cover lookup"}});if(!response.ok)return[];const html=await response.text(),heading=html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1],pageTitle=heading?htmlText(heading):"";if(pageTitle){const e=titleVariants(title).map(v=>titleEvidence(v,pageTitle)).sort((a,b)=>b.score-a.score)[0];if(!e||!(e.exact||e.adjacent||e.coverage>=.5||e.keywordMatches>=2))return[];}const header=html.slice(0,30000),am=header.match(/\bby\s*<a[^>]*>([\s\S]*?)<\/a>/i)?.[1],pa=am?htmlText(am):"";if(author&&pa&&authorEvidence(author,[pa])<3)return[];const start=html.search(/Popular Covers/i);if(start<0)return[];const tail=html.slice(start,start+60000),end=tail.search(/Find It/i),section=end>0?tail.slice(0,end):tail,urls:string[]=[];for(const m of section.matchAll(/<img\b[^>]*\b(?:src|data-src)=["']([^"']+)["'][^>]*>/gi)){let url=decodeHtml(m[1]);if(!/^(?:https?:)?\/\/pics(?:\.cdn)?\.librarything\.com\/picsizes\//i.test(url))continue;if(url.startsWith("//"))url=`https:${url}`;url=url.replace(/^http:\/\//i,"https://");if(!urls.includes(url))urls.push(url);if(urls.length>=20)break;}return urls.map((url,index)=>({url,source:"LibraryThing",score:18.5-index*.02}));}catch{return[];}}
function openLibraryCoverById(id?:number){return id?`https://covers.openlibrary.org/b/id/${id}-L.jpg`:null;}
async function openLibraryCoverByIsbn(isbn:string):Promise<CoverOption[]>{const key=`ISBN:${isbn}`,response=await fetch(`https://openlibrary.org/api/books?bibkeys=${encodeURIComponent(key)}&format=json&jscmd=data`,{next:{revalidate:86400}});if(!response.ok)return[];const data=await response.json() as Record<string,OpenLibraryBook>,cover=data[key]?.cover,image=httpsImage(cover?.large||cover?.medium||cover?.small);return image?[{url:image,source:"Open Library",score:30}]:[];}
async function openLibrarySearchByIsbn(isbn:string):Promise<CoverOption[]>{const params=new URLSearchParams({isbn,fields:"cover_i",limit:"10"}),response=await fetch(`https://openlibrary.org/search.json?${params}`,{next:{revalidate:86400}});if(!response.ok)return[];const data=await response.json() as OpenLibrarySearchResponse;return(data.docs||[]).flatMap((doc,index)=>{const image=openLibraryCoverById(doc.cover_i);return image?[{url:image,source:"Open Library",score:28-index*.1}]:[];});}
async function openLibraryMatches(url:string,title:string,author:string):Promise<CoverOption[]>{const response=await fetch(url,{next:{revalidate:86400}});if(!response.ok)return[];const data=await response.json() as OpenLibrarySearchResponse,results:CoverOption[]=[];for(const doc of data.docs||[]){const image=openLibraryCoverById(doc.cover_i);if(!image)continue;const match=matchCandidate(title,author,doc.title,doc.author_name||[]);if(match.accepted)results.push({url:image,source:"Open Library",score:match.score});}return results;}
async function openLibrarySearchByTitle(searchTitle:string,title:string,author:string){const p=new URLSearchParams({title:searchTitle,fields:"title,author_name,cover_i",limit:"40"});if(author)p.set("author",author);return openLibraryMatches(`https://openlibrary.org/search.json?${p}`,title,author);}
async function openLibraryKeywordSearch(searchTitle:string,title:string,author:string){const q=keywordSearchText(searchTitle,author);if(!q)return[];return openLibraryMatches(`https://openlibrary.org/search.json?${new URLSearchParams({q,fields:"title,author_name,cover_i",limit:"40"})}`,title,author);}
async function openLibraryBareKeywordSearch(searchTitle:string,title:string,author:string){const q=titleKeywords(searchTitle).slice(0,5).join(" ");if(!q)return[];return openLibraryMatches(`https://openlibrary.org/search.json?${new URLSearchParams({q,fields:"title,author_name,cover_i",limit:"40"})}`,title,author);}
function googleImage(book:GoogleBook){const i=book.volumeInfo?.imageLinks;return httpsImage(i?.extraLarge||i?.large||i?.medium||i?.small||i?.thumbnail||i?.smallThumbnail)||null;}
async function googleBooksCovers(query:string,title="",author="",trustFirst=false):Promise<CoverOption[]>{const response=await fetch(`https://www.googleapis.com/books/v1/volumes?${new URLSearchParams({q:query,maxResults:"40",printType:"books"})}`,{next:{revalidate:86400}});if(!response.ok)return[];const data=await response.json() as GoogleBooksResponse,results:CoverOption[]=[];for(const[index,item]of(data.items||[]).entries()){const image=googleImage(item);if(!image)continue;if(trustFirst){results.push({url:image,source:"Google Books",score:29-index*.1});continue;}const match=matchCandidate(title,author,item.volumeInfo?.title,item.volumeInfo?.authors||[]);if(match.accepted)results.push({url:image,source:"Google Books",score:match.score+.25});}return results;}
function uniqueRanked(options:CoverOption[]){const seen=new Set<string>();return options.sort((a,b)=>b.score-a.score).filter(o=>{const key=o.url.replace(/&zoom=\d+/i,"");if(seen.has(key))return false;seen.add(key);return true;}).slice(0,60).map(({url,source})=>({url,source}));}
export async function GET(request:NextRequest){const isbn=request.nextUrl.searchParams.get("isbn")?.trim()||"",title=request.nextUrl.searchParams.get("title")?.trim()||"",author=request.nextUrl.searchParams.get("author")?.trim()||"",includeLibraryThing=request.nextUrl.searchParams.get("libraryThing")==="1";let discoveredIsbn="";try{const searches:Promise<CoverOption[]>[]=[];if(isbn){searches.push(amazonHighResCoverByIsbn(isbn));searches.push(openLibraryCoverByIsbn(isbn));searches.push(openLibrarySearchByIsbn(isbn));searches.push(googleBooksCovers(`isbn:${isbn}`,title,author,true));}if(title){for(const searchTitle of titleVariants(title)){searches.push(openLibrarySearchByTitle(searchTitle,title,author),openLibraryKeywordSearch(searchTitle,title,author),openLibraryBareKeywordSearch(searchTitle,title,author));const strict=author?`intitle:${searchTitle} inauthor:${author}`:`intitle:${searchTitle}`;searches.push(googleBooksCovers(strict,title,author),googleBooksCovers(author?`${searchTitle} ${author}`:searchTitle,title,author));const keyword=keywordSearchText(searchTitle,author);if(keyword)searches.push(googleBooksCovers(keyword,title,author));const bare=titleKeywords(searchTitle).slice(0,5).join(" ");if(bare&&normalizeText(bare)!==normalizeText(keyword))searches.push(googleBooksCovers(bare,title,author));const last=textWords(author).at(-1);if(last&&bare)searches.push(googleBooksCovers(`${bare} inauthor:${last}`,title,author));}}
const groups=await Promise.allSettled(searches);let candidates=groups.flatMap(g=>g.status==="fulfilled"?g.value:[]);if(includeLibraryThing){try{let editionIsbns:string[]=[];if(isbn){editionIsbns=[isbn,...await libraryThingRelatedIsbns(isbn)];}else if(title){editionIsbns=await libraryThingIsbnsByTitle(title);discoveredIsbn=editionIsbns[0]||"";}const deeper:Promise<CoverOption[]>[]=[];for(const[index,editionIsbn]of editionIsbns.entries()){deeper.push(amazonHighResCoverByIsbn(editionIsbn),openLibraryCoverByIsbn(editionIsbn),openLibrarySearchByIsbn(editionIsbn),googleBooksCovers(`isbn:${editionIsbn}`,title,author,!discoveredIsbn));if(index>=9)break;}const[deepGroups,gallery]=await Promise.all([Promise.allSettled(deeper),title?libraryThingPopularCoversByTitle(title,author):Promise.resolve([])]);const related=deepGroups.flatMap(g=>g.status==="fulfilled"?g.value:[]).map((o,index)=>({...o,score:o.source==="Amazon High-Res"?34.5:Math.min(o.score,19.5-index*.01)}));candidates=[...candidates,...related,...gallery];}catch{}}
const options=uniqueRanked(candidates);if(options.length)return NextResponse.json({...options[0],options,...(discoveredIsbn?{discoveredIsbn}:{})},{headers:includeLibraryThing?{"Cache-Control":"no-store"}:responseHeaders});if(discoveredIsbn)return NextResponse.json({url:null,source:null,options:[],discoveredIsbn},{headers:{"Cache-Control":"no-store"}});}catch{}return NextResponse.json({url:null,source:null,options:[]},{status:404,headers:{"Cache-Control":includeLibraryThing?"no-store":"public, s-maxage=3600"}});}
