"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import "./help-the-shelf.css";

const SUPABASE_URL="https://vrkuimrfdkejfhpxlwlf.supabase.co";
const SUPABASE_KEY="sb_publishable_mf0u925xGBkP4iNgxSCjuQ_H4Dp8r1S";
const SESSION_KEY="shelf-of-fame-supabase-session";
type Candidate={id:string;image_url:string;book_id?:string|null;source_title?:string|null;source_author?:string|null;status:string;books?:{title?:string;author?:string}|null};
function token(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null")?.access_token as string|undefined}catch{return undefined}}
function headers(){const t=token();return{apikey:SUPABASE_KEY,"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})}}

export default function HelpTheShelf(){
 const [candidate,setCandidate]=useState<Candidate|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [done,setDone]=useState(0);
 const load=useCallback(async()=>{setLoading(true);setMessage("");try{const t=token();if(!t){setCandidate(null);setMessage("Sign in first so we can credit your contribution.");return}const voted=await fetch(`${SUPABASE_URL}/rest/v1/cover_candidate_votes?select=candidate_id&user_id=eq.${encodeURIComponent(JSON.parse(localStorage.getItem(SESSION_KEY)||"null")?.user?.id||"")}`,{headers:headers()});const ids=voted.ok?(await voted.json()).map((x:{candidate_id:string})=>x.candidate_id):[];const q=`${SUPABASE_URL}/rest/v1/cover_candidates?select=id,image_url,book_id,source_title,source_author,status,books(title,author)&status=in.(pending,needs_identification)&order=created_at.asc&limit=25`;const r=await fetch(q,{headers:headers()});if(!r.ok)throw new Error("Could not load community tasks.");const rows:Candidate[]=await r.json();const next=rows.find(x=>!ids.includes(x.id))||null;setCandidate(next);if(!next)setMessage("You're caught up! More covers will appear as the shared catalog grows.")}catch(e){setMessage(e instanceof Error?e.message:"Could not load a task.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function vote(v:string){if(!candidate)return;setLoading(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/submit_cover_vote`,{method:"POST",headers:headers(),body:JSON.stringify({p_candidate_id:candidate.id,p_vote:v})});if(!r.ok)throw new Error("Could not save your vote.");setDone(x=>x+1);await load()}catch(e){setMessage(e instanceof Error?e.message:"Could not save vote");setLoading(false)}}
 async function identify(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!candidate)return;const f=new FormData(e.currentTarget),title=String(f.get("title")||"").trim(),author=String(f.get("author")||"").trim();setLoading(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/submit_cover_identification`,{method:"POST",headers:headers(),body:JSON.stringify({p_candidate_id:candidate.id,p_title:title,p_author:author})});if(!r.ok)throw new Error("Could not save that identification.");setDone(x=>x+1);await load()}catch(err){setMessage(err instanceof Error?err.message:"Could not save identification");setLoading(false)}}
 const known=candidate?.books?.title||candidate?.source_title; const author=candidate?.books?.author||candidate?.source_author; const identifyMode=candidate?.status==="needs_identification"||!known;
 return <main className="help-shell"><header><a href="/">← My Shelf</a><div><strong>HELP THE SHELF</strong><span>{done} helped this session</span></div><a href="/account">Account</a></header><section className="help-intro"><p>COMMUNITY LIBRARY</p><h1>{identifyMode?"What book is this?":"Is this the right cover?"}</h1><span>{identifyMode?"Identify the cover so future readers can find it.":"Your vote helps connect artwork to the correct book and edition."}</span></section>{loading&&!candidate?<div className="help-empty">Loading the next cover…</div>:candidate?<div className="help-card"><div className="help-cover"><img src={candidate.image_url} alt="Book cover to verify" /></div>{identifyMode?<form onSubmit={identify}><label>Book title<input name="title" required maxLength={300} autoComplete="off" placeholder="Enter the title" /></label><label>Author<input name="author" required maxLength={200} autoComplete="off" placeholder="Enter the author" /></label><button disabled={loading} className="identify">Submit identification</button><button type="button" className="skip" onClick={()=>void load()}>Not sure — skip</button></form>:<div className="help-question"><h2>{known}</h2><p>{author||"Unknown author"}</p><div className="vote-grid"><button disabled={loading} onClick={()=>void vote("correct")} className="yes">✓ Correct</button><button disabled={loading} onClick={()=>void vote("wrong")} className="no">✕ Wrong</button><button disabled={loading} onClick={()=>void vote("different_edition")} className="edition">Different edition</button><button disabled={loading} onClick={()=>void load()} className="skip">Not sure — skip</button></div></div>}</div>:<div className="help-empty">{message||"No community tasks yet."}</div>}{message&&candidate&&<p className="help-message">{message}</p>}</main>
}
